ISalesProducts/ISalesProducts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from userextend.forms import AuthenticationNewForm, PasswordChangeNewForm, PasswordResetNewForm, SetPasswordNewForm

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("", include('resume.urls')),
    path("login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name="login"),
    path("password_change/", views.PasswordChangeView.as_view(form_class=PasswordChangeNewForm), name='password_change'),
    path("password_reset/", views.PasswordResetView.as_view(form_class=PasswordResetNewForm), name='password_reset'),
    path("reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(form_class=SetPasswordNewForm), name='password_reset_confim'),
    path('', include('django.contrib.auth.urls')),
    path('', include('userextend.urls')),
    path('', include('category.urls')),
    path('', include('product.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ISalesProducts/home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='homepage')
]

ISalesProducts/category/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50)
    active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

ISalesProducts/product/models.py
from django.db import models

from category.models import Category


class Product(models.Model):
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50)
    price = models.CharField(max_length=30)
    description = models.TextField(max_length=100)
    image = models.FileField(upload_to='photos/', null=True)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name} from {self.category.name}'

ISalesProducts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link href="{% static 'css/my_style.css' %}" rel="stylesheet">
</head>
<body>
{% include 'navbar.html' %}
{% block content %} {% endblock %}
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
</html>

ISalesProducts/templates/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        .edit_a {
            background-color: #a42b2b;
            color: white;
            text-align: center;
            text-decoration: none;
            padding: 14px 25px;

        }
    </style>
</head>
<body>
<div>
    <h2>Hello, {{ fullname }}</h2>
    <h4>Congratulations! Your account has been created</h4>
    <br>
    <h4>Your username account is: {{ user_name }}</h4>

    <a class="edit_a" href="http://localhost:8001/login/">Go to login</a>
</div>

</body>
</html>

ISalesProducts/templates/mail_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
<div>
    <h2>Hello, {{ fullname }}</h2>
    <h4>Congratulations! Your account has been created</h4>

    <a href="http://localhost:8001/homepage/" style="background-color: #a42b2b;
        color: white; padding: 14px 25px; text-decoration: none;  text-align: center">Go to login</a>
</div>

</body>
</html>

ISalesProducts/templates/navbar.html
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Online Store</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'homepage' %}">Acasa</a>
        </li>
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'resume' %}">Resume</a>
        </li>
      {% endif %}
      {% if perms.user.add_category or user.is_authenticated%}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'create-category' %}">Create Category</a></li>
            <li><a class="dropdown-item" href="{% url 'list-of-category' %}">List of Categories</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
       {% endif %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Products
          </a>
          <ul class="dropdown-menu">
              {% if perms.user.add_product %}
                <li><a class="dropdown-item" href="{% url 'create-product' %}">Create Product</a></li>
              {% endif %}
            <li><a class="dropdown-item" href="{% url 'list-of-products' %}">List of Products</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                List of Categories</a>
            <ul class="dropdown-menu">
                {% for category in categories %}
                    <li><a class="dropdown-item" href="{% url 'products-per-category' category.id %}">
                    {{ category }}</a>
                    </li>
                {% endfor %}
            </ul>
        </li>
      </ul>
        {% if user.is_authenticated %}
        <div class="btn-group dropstart">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown"
                    aria-expanded="false">
                My Profile, {{ user }}
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password</a></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </div>
        {% else %}
        <div class="btn-group dropstart">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown"
                    aria-expanded="false">
                Sign In
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                <li><a class="dropdown-item" href="{% url 'create-user' %}">Sign up</a></li>
            </ul>
        </div>
        {% endif %}
    </div>
  </div>
</nav>